[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "year2015"
dynamic = ["version"]
dependencies = []
requires-python = ">=3.12"
description = "TODO"
readme = "README.md"

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-datadir",
]
