[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "year2015"
dynamic = ["version"]
dependencies = [
    "pytest",
    "pytest-datadir",
]
requires-python = ">=3.12"
description = "TODO"
readme = "README.md"
