name: Python

on: push

defaults:
  run:
    working-directory: ./year2015

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Lint and format
        uses: astral-sh/ruff-action@v1
